name: .NET Web-App ForecastBot

on:
  push:
    branches: [ master,development ]
  pull_request:
    branches: [ master,development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ForecastBot RUN
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Build ForecastBot
      run: dotnet build ./src/WeatherNotifier/ForecastBot.csproj --configuration Release
      
    - name: Send mail
      if: always()
      uses: actions/checkout@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: ice19942335@gmail.com
        # from email name
        from: Aleksejs Birula
