name: .NET Web-App ForecastBot

on:
  push:
    branches: [ master,development ]
  pull_request:
    branches: [ master,development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ForecastBot RUN
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Build ForecastBot
      run: dotnet build ./src/WeatherNotifier/ForecastBot.csproj --configuration Release
